### PR TITLE
Remove dco check in github action.

### PR DESCRIPTION
**Pull request by xuezhaojun**
We already have a dco check in prow, and github action doc check is not always align with prow's result.

It also blocks this PR from redaht TAP. https://github.com/stolostron/managedcluster-import-controller/pull/231

### CODE REVIEW

**Comment by zhujian7** [comment]
@qiujian16 WDYT?

**Comment by xuezhaojun** [comment]
The latest blocked PR: https://github.com/stolostron/managedcluster-import-controller/pull/285

**Pull request merged**
