### PR TITLE
parse CA bundle before comparing it with the original one

### PR DESCRIPTION
**Pull request by elgnay**
https://issues.redhat.com/browse/ACM-10735

### CODE REVIEW

**Review by xuezhaojun — COMMENTED** [review]
It looks like these 3 functions always shows up together:
```go
apiServerCAData, err := bootstrap.GetBootstrapCAData(ctx, clientHolder, kubeAPIServer, clusterName, klusterletConfig)
	if err != nil {
		return false, err
	}

	_, proxyCAData := bootstrap.GetProxySettings(klusterletConfig)
	currentCAData, err := bootstrap.MergeCertificateData(apiServerCAData, proxyCAData)
	if err != nil {
		return false, err
	}
```

Do we consider embed `GetProxySetting` and `MergeCertificateData` into `GetBootstrapCAData`?

**Comment by elgnay** [comment]
> It looks like these 3 functions always shows up together:
> 
> ```go
> apiServerCAData, err := bootstrap.GetBootstrapCAData(ctx, clientHolder, kubeAPIServer, clusterName, klusterletConfig)
> 	if err != nil {
> 		return false, err
> 	}
> 
> 	_, proxyCAData := bootstrap.GetProxySettings(klusterletConfig)
> 	currentCAData, err := bootstrap.MergeCertificateData(apiServerCAData, proxyCAData)
> 	if err != nil {
> 		return false, err
> 	}
> ```
> 
> Do we consider embed `GetProxySetting` and `MergeCertificateData` into `GetBootstrapCAData`?

It makes sense. Code updated as suggested.

**Comment by xuezhaojun** [comment]
/hold 
@zhujian7 Please unhold if you feel good to go ahead

**Pull request merged**
