### PR TITLE
support klusterletconfig with proxyconfig

### PR DESCRIPTION
**Pull request by elgnay**
The related issue: https://issues.redhat.com/browse/ACM-6325

### CODE REVIEW

**Comment by xuezhaojun** [comment]
We may need to upgrade crd yaml used in e2e in this PR as well: cd9b187cca82

**Comment by elgnay** [comment]
> @elgnay We may need to upgrade crd yaml used in e2e in this PR as well: https://github.com/stolostron/managedcluster-import-controller/blob/main/deploy/base/config.open-cluster-management.io_klusterletconfig.crd.yaml

Upgraded.

**Pull request merged**
